#!/bin/bash

## Copying data from wheeler
ORIGIN_DIR=mokounko@wheeler.caltech.edu:/home/mokounko/Data/EDGBEvolutionCorrect_ScalarField_Symm
DATA_DIR=/Users/mokounkova/EDGB/Evolution/Runs_Correct_ScalarField_Symm

rsync -r ${ORIGIN_DIR}/Joined* $DATA_DIR

